In [ ]:
# !pip install seaborn

In [1]:
# import toolkit
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from datetime import date
import pandas as pd

In [2]:
# import sentimental data
amazon_df = pd.read_csv('amazon_df.csv')
gme_df = pd.read_csv('gme_df.csv')
kodak_df = pd.read_csv('kodak_df.csv')
facebook_df = pd.read_csv('fb_df.csv')
apple_df = pd.read_csv('new_data/aapl_df.csv')
baba_df = pd.read_csv('new_data/baba_df.csv')
goog_df = pd.read_csv('new_data/goog_df.csv')
jnj_df = pd.read_csv('new_data/jnj_df.csv')
pfe_df = pd.read_csv('new_data/pfe_df.csv')
tsla_df = pd.read_csv('new_data/tsla_df.csv')

In [3]:
# renaming columns
amazon_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
gme_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
kodak_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
facebook_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
goog_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
apple_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
baba_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
jnj_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
pfe_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
tsla_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)

# dropping columns

amazon_df.drop(columns=['Unnamed: 0'], inplace=True)
gme_df.drop(columns=['Unnamed: 0'], inplace=True)
kodak_df.drop(columns=['Unnamed: 0'], inplace=True)
facebook_df.drop(columns=['Unnamed: 0'], inplace=True)
apple_df.drop(columns=['Unnamed: 0'], inplace=True)
goog_df.drop(columns=['Unnamed: 0'], inplace=True)
baba_df.drop(columns=['Unnamed: 0'], inplace=True)
jnj_df.drop(columns=['Unnamed: 0'], inplace=True)
pfe_df.drop(columns=['Unnamed: 0'], inplace=True)
tsla_df.drop(columns=['Unnamed: 0'], inplace=True)

In [4]:
# import price data
amazon_price_df = pd.read_csv('price/AMZN_1.csv')
gme_price_df = pd.read_csv('price/GME_1.csv')
kodak_price_df = pd.read_csv('price/KODK_1.csv')
facebook_price_df = pd.read_csv('price/FB_1.csv')
apple_price_df = pd.read_csv('price/AAPL.csv')
baba_price_df = pd.read_csv('price/BABA.csv')
goog_price_df = pd.read_csv('price/GOOG.csv')
jnj_price_df = pd.read_csv('price/JNJ.csv')
pfe_price_df = pd.read_csv('price/PFE.csv')
tsla_price_df = pd.read_csv('price/TSLA.csv')

In [5]:
# merging DB

amazon_df = pd.merge(amazon_df, amazon_price_df, how="outer", on=["Date", "Date"])
gme_df = pd.merge(gme_df, gme_price_df, how="outer", on=["Date", "Date"] )
kodak_df = pd.merge(kodak_df, kodak_price_df, how="outer", on=["Date", "Date"] )
facebook_df = pd.merge(facebook_df, facebook_price_df, how="outer", on=["Date", "Date"] )
apple_df = pd.merge(apple_df, apple_price_df, how="outer", on=["Date", "Date"] )
baba_df = pd.merge(baba_df, baba_price_df, how="outer", on=["Date", "Date"] )
goog_df = pd.merge(goog_df, goog_price_df, how="outer", on=["Date", "Date"] )
jnj_df = pd.merge(jnj_df, jnj_price_df, how="outer", on=["Date", "Date"] )
pfe_df = pd.merge(pfe_df, pfe_price_df, how="outer", on=["Date", "Date"] )
tsla_df = pd.merge(tsla_df, tsla_price_df, how="outer", on=["Date", "Date"] )


print(amazon_df.shape)
print(kodak_df.shape)
print(gme_df.shape)
print(facebook_df.shape)

(862, 11)
(653, 11)
(726, 11)
(855, 11)


In [6]:
facebook_df.drop(columns=['Date'],inplace=True)
kodak_df.drop(columns=['Date'],inplace=True)
gme_df.drop(columns=['Date'],inplace=True)
amazon_df.drop(columns=['Date'],inplace=True)
apple_df.drop(columns=['Date'],inplace=True)
goog_df.drop(columns=['Date'],inplace=True)
baba_df.drop(columns=['Date'],inplace=True)
jnj_df.drop(columns=['Date'],inplace=True)
pfe_df.drop(columns=['Date'],inplace=True)
tsla_df.drop(columns=['Date'],inplace=True)


In [7]:
facebook_df['retorno'] = facebook_df['Close'].pct_change()
kodak_df['retorno'] = kodak_df['Close'].pct_change()
gme_df['retorno'] = gme_df['Close'].pct_change()
amazon_df['retorno'] = amazon_df['Close'].pct_change()
apple_df['retorno'] = apple_df['Close'].pct_change()
goog_df['retorno'] = goog_df['Close'].pct_change()
baba_df['retorno'] = baba_df['Close'].pct_change()
jnj_df['retorno'] = jnj_df['Close'].pct_change()
pfe_df['retorno'] = pfe_df['Close'].pct_change()

In [8]:
from sklearn.impute import KNNImputer, SimpleImputer

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
preprocessor = ColumnTransformer([('imputer',  KNNImputer(n_neighbors=1),['Open','Low','Close','Adj Close', 'Volume'])], remainder='passthrough')
filling_na = SimpleImputer(strategy="constant", fill_value=-1000)
my_pipeline = Pipeline(steps=[('preprocessor', preprocessor),('fill_na', filling_na)])

In [10]:
facebook_df.isna().sum()

Positive               8
Neutral                8
Negative               8
Sentimental Score      8
Open                 219
High                 219
Low                  219
Close                219
Adj Close            219
Volume               219
retorno                2
dtype: int64

In [11]:
#facebook_df = facebook_df[['Open','Low','Close','Adj Close', 'Volume']].apply(lambda x:preprocessor.fit_transform(x))
gme_np = my_pipeline.fit_transform(gme_df) 
gme_np

array([[ 1.60000000e+02,  1.58009995e+02,  1.66820007e+02, ...,
        -6.67000000e-01,  1.71990005e+02, -1.00000000e+03],
       [ 1.80490005e+02,  1.65070007e+02,  1.67619995e+02, ...,
         5.00000000e-01,  1.82380005e+02,  4.79551592e-03],
       [ 1.87679993e+02,  1.79000000e+02,  1.80059998e+02, ...,
         1.30000000e+00,  1.88789993e+02,  7.42155075e-02],
       ...,
       [ 1.85300003e+02,  1.76149994e+02,  1.78850006e+02, ...,
        -1.00000000e+03,  1.87690002e+02, -3.74575753e-02],
       [ 1.81000000e+02,  1.73839996e+02,  1.80360001e+02, ...,
        -1.00000000e+03,  1.81600006e+02,  8.44280095e-03],
       [ 1.80360001e+02,  1.78759995e+02,  1.83940002e+02, ...,
        -1.00000000e+03,  1.86039993e+02,  1.98491959e-02]])

In [25]:
gme_np = my_pipeline.fit_transform(gme_df) 
kodak_np = my_pipeline.fit_transform(kodak_df)
facebook_np = my_pipeline.fit_transform(facebook_df)
amazon_np = my_pipeline.fit_transform(amazon_df)
apple_np = my_pipeline.fit_transform(apple_df)
google_np = my_pipeline.fit_transform(goog_df)
baba_np = my_pipeline.fit_transform(baba_df)
jnj_np = my_pipeline.fit_transform(jnj_df)
pfe_np = my_pipeline.fit_transform(pfe_df)


In [26]:
news_stock_np = np.array([gme_np,kodak_np,amazon_np,facebook_np, apple_np, google_np, baba_np, jnj_np, pfe_np])

/var/folders/rl/l0hlsnhd3_zcy_9mm8jb32n00000gn/T/ipykernel_25005/2297827910.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  news_stock_np = np.array([gme_np,kodak_np,amazon_np,facebook_np, apple_np, google_np, baba_np, jnj_np, pfe_np])


In [27]:
news_stock_np

array([array([[ 1.60000000e+02,  1.58009995e+02,  1.66820007e+02, ...,
        -6.67000000e-01,  1.71990005e+02, -1.00000000e+03],
       [ 1.80490005e+02,  1.65070007e+02,  1.67619995e+02, ...,
         5.00000000e-01,  1.82380005e+02,  4.79551592e-03],
       [ 1.87679993e+02,  1.79000000e+02,  1.80059998e+02, ...,
         1.30000000e+00,  1.88789993e+02,  7.42155075e-02],
       ...,
       [ 1.85300003e+02,  1.76149994e+02,  1.78850006e+02, ...,
        -1.00000000e+03,  1.87690002e+02, -3.74575753e-02],
       [ 1.81000000e+02,  1.73839996e+02,  1.80360001e+02, ...,
        -1.00000000e+03,  1.81600006e+02,  8.44280095e-03],
       [ 1.80360001e+02,  1.78759995e+02,  1.83940002e+02, ...,
        -1.00000000e+03,  1.86039993e+02,  1.98491959e-02]]),
       array([[ 7.41000000e+00,  7.25000000e+00,  7.39000000e+00, ...,
        -1.50000000e+00,  7.76000000e+00, -1.00000000e+03],
       [ 8.14000000e+00,  7.86000000e+00,  7.98000000e+00, ...,
         1.00000000e+00,  8.16000000e+00

In [28]:
#reddit_day.fillna(-1000,inplace=True)
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [29]:
news_stock_np.shape

(9,)

In [30]:
news_stock_np_pad = pad_sequences(news_stock_np,value=-1000, dtype='float32') # int32 by default
news_stock_np_pad

array([[[-1.0000000e+03, -1.0000000e+03, -1.0000000e+03, ...,
         -1.0000000e+03, -1.0000000e+03, -1.0000000e+03],
        [-1.0000000e+03, -1.0000000e+03, -1.0000000e+03, ...,
         -1.0000000e+03, -1.0000000e+03, -1.0000000e+03],
        [-1.0000000e+03, -1.0000000e+03, -1.0000000e+03, ...,
         -1.0000000e+03, -1.0000000e+03, -1.0000000e+03],
        ...,
        [ 1.8530000e+02,  1.7614999e+02,  1.7885001e+02, ...,
         -1.0000000e+03,  1.8769000e+02, -3.7457574e-02],
        [ 1.8100000e+02,  1.7384000e+02,  1.8036000e+02, ...,
         -1.0000000e+03,  1.8160001e+02,  8.4428005e-03],
        [ 1.8036000e+02,  1.7875999e+02,  1.8394000e+02, ...,
         -1.0000000e+03,  1.8603999e+02,  1.9849196e-02]],

       [[-1.0000000e+03, -1.0000000e+03, -1.0000000e+03, ...,
         -1.0000000e+03, -1.0000000e+03, -1.0000000e+03],
        [-1.0000000e+03, -1.0000000e+03, -1.0000000e+03, ...,
         -1.0000000e+03, -1.0000000e+03, -1.0000000e+03],
        [-1.0000000e+03, 

In [31]:
news_stock_np_pad.shape

(9, 862, 11)

In [32]:
x=news_stock_np_pad[:,:-1,:]
x.shape

(9, 861, 11)

In [33]:
y=news_stock_np_pad[:,-1,-1]
y.shape

(9,)

In [43]:
y_train =y[0:6]
y_test = y[-3:]

In [44]:
x_train = x[0:6,:,:]
x_test = x[-3:,:,:]

In [45]:
y_test

array([-0.03508687,  0.0106483 ,  0.00506388], dtype=float32)

In [46]:
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.layers.experimental.preprocessing import Normalization
def init_model():
    #normalizar o x train
    normalizer = Normalization()
    model = models.Sequential()
    model.add(layers.Masking(mask_value=-1000.))
    normalizer.adapt(x_train)
    model.add(layers.LSTM(20, return_sequences=True, activation='tanh'))
    model.add(layers.LSTM(10, return_sequences=False, activation='tanh'))
    model.add(layers.Dense(5, activation='relu'))
    model.add(layers.Dense(10, activation='linear'))
    
  #  model.compile(loss='mse', 
  #                optimizer='rmsprop', 
  #                metrics=['mae'])
    model.compile(loss='mse', 
                  optimizer=RMSprop(learning_rate=0.0003), 
                  metrics=['mae'])
    
    return model

#init_model().summary()

In [47]:
model=init_model()

2021-07-31 16:11:01.654534: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)


In [48]:
model.fit(x_train,y_train,epochs=20)

Epoch 1/20
1/1 [==============================] - 16s 16s/step - loss: 0.2409 - mae: 0.2439
Epoch 2/20
1/1 [==============================] - 1s 1s/step - loss: 0.2501 - mae: 0.2164
Epoch 3/20
1/1 [==============================] - 1s 1s/step - loss: 0.2498 - mae: 0.2158
Epoch 4/20
1/1 [==============================] - 1s 1s/step - loss: 0.2496 - mae: 0.2154
Epoch 5/20
1/1 [==============================] - 1s 1s/step - loss: 0.2494 - mae: 0.2150
Epoch 6/20
1/1 [==============================] - 1s 1s/step - loss: 0.2492 - mae: 0.2147
Epoch 7/20
1/1 [==============================] - 1s 1s/step - loss: 0.2490 - mae: 0.2144
Epoch 8/20
1/1 [==============================] - 2s 2s/step - loss: 0.2488 - mae: 0.2141
Epoch 9/20
1/1 [==============================] - 1s 1s/step - loss: 0.2486 - mae: 0.2139
Epoch 10/20
1/1 [==============================] - 1s 1s/step - loss: 0.2485 - mae: 0.2136
Epoch 11/20
1/1 [==============================] - 1s 1s/step - loss: 0.2483 - mae: 0.2134
Epoch 

Positive  Neutral  Negative  Sentimental Score        Open        High  \
0         0.0      4.0       8.0             -0.667  160.000000  171.990005   
1         2.0      0.0       1.0              0.500  180.490005  182.380005   
2         3.0      2.0       0.0              1.300  187.679993  188.789993   
3         2.0      0.0       0.0              1.500  191.419998  197.750000   
4         0.0      0.0       1.0             -1.500         NaN         NaN   
..        ...      ...       ...                ...         ...         ...   
721       NaN      NaN       NaN                NaN  173.899994  193.639999   
722       NaN      NaN       NaN                NaN  187.789993  195.509995   
723       NaN      NaN       NaN                NaN  185.300003  187.690002   
724       NaN      NaN       NaN                NaN  181.000000  181.600006   
725       NaN      NaN       NaN                NaN  180.360001  186.039993   

            Low       Close   Adj Close     Volume   retorno  
0    158.009995  166.820007  166.820007  4298600.0       NaN  
1    165.070007  167.619995  167.619995  3913800.0  0.004796  
2    179.000000  180.059998  180.059998  2397900.0  0.074216  
3    187.419998  189.250000  189.250000  1636300.0  0.051039  
4           NaN         NaN         NaN        NaN  0.000000  
..          ...         ...         ...        ...       ...  
721  172.419998  191.179993  191.179993  3101100.0  0.101965  
722  182.110001  185.809998  185.809998  2229200.0 -0.028089  
723  176.149994  178.850006  178.850006  1413000.0 -0.037458  
724  173.839996  180.360001  180.360001  1312900.0  0.008443  
725  178.759995  183.940002  183.940002  1255400.0  0.019849  

[726 rows x 11 columns]

In [75]:
predict_y = model.predict(gme_df)

ValueError: in user code:

    /Users/netoconcon/.pyenv/versions/3.8.6/envs/next_trend/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1569 predict_function  *
        return step_function(self, iterator)
    /Users/netoconcon/.pyenv/versions/3.8.6/envs/next_trend/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1559 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /Users/netoconcon/.pyenv/versions/3.8.6/envs/next_trend/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /Users/netoconcon/.pyenv/versions/3.8.6/envs/next_trend/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /Users/netoconcon/.pyenv/versions/3.8.6/envs/next_trend/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    /Users/netoconcon/.pyenv/versions/3.8.6/envs/next_trend/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1552 run_step  **
        outputs = model.predict_step(data)
    /Users/netoconcon/.pyenv/versions/3.8.6/envs/next_trend/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1525 predict_step
        return self(x, training=False)
    /Users/netoconcon/.pyenv/versions/3.8.6/envs/next_trend/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:1030 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    /Users/netoconcon/.pyenv/versions/3.8.6/envs/next_trend/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py:380 call
        return super(Sequential, self).call(inputs, training=training, mask=mask)
    /Users/netoconcon/.pyenv/versions/3.8.6/envs/next_trend/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py:420 call
        return self._run_internal_graph(
    /Users/netoconcon/.pyenv/versions/3.8.6/envs/next_trend/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py:556 _run_internal_graph
        outputs = node.layer(*args, **kwargs)
    /Users/netoconcon/.pyenv/versions/3.8.6/envs/next_trend/lib/python3.8/site-packages/tensorflow/python/keras/layers/recurrent.py:668 __call__
        return super(RNN, self).__call__(inputs, **kwargs)
    /Users/netoconcon/.pyenv/versions/3.8.6/envs/next_trend/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:1013 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /Users/netoconcon/.pyenv/versions/3.8.6/envs/next_trend/lib/python3.8/site-packages/tensorflow/python/keras/engine/input_spec.py:215 assert_input_compatibility
        raise ValueError('Input ' + str(input_index) + ' of layer ' +

    ValueError: Input 0 of layer lstm is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (None, 11)


In [54]:
predict_y

array([[0.00873057, 0.00833398, 0.00869733, 0.00836744, 0.00824956,
        0.00880485, 0.00888902, 0.00889627, 0.00873687, 0.00844089],
       [0.00873057, 0.00833398, 0.00869733, 0.00836744, 0.00824956,
        0.00880485, 0.00888902, 0.00889627, 0.00873687, 0.00844089],
       [0.00873057, 0.00833398, 0.00869733, 0.00836744, 0.00824956,
        0.00880485, 0.00888902, 0.00889627, 0.00873687, 0.00844089]],
      dtype=float32)

In [55]:
y_test

array([-0.03508687,  0.0106483 ,  0.00506388], dtype=float32)

new approach

In [76]:
from keras.preprocessing.sequence import TimeseriesGenerator

In [80]:
data_gen = TimeseriesGenerator(gme_df.drop(columns=['retorno']).to_numpy(), gme_df['retorno'].to_numpy(),
                               length=10, sampling_rate=2,
                               batch_size=2)

In [85]:
data_gen[0][0].shape
# (batch size, tamanho, features)

(2, 5, 10)

In [88]:
model2 = init_model()

model2.fit_generator(data_gen)

/Users/netoconcon/.pyenv/versions/3.8.6/envs/next_trend/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1940: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


ValueError: Failed to find data adapter that can handle input: <class 'keras.preprocessing.sequence.TimeseriesGenerator'>, <class 'NoneType'>