In [ ]:
# !pip install seaborn

In [1]:
# import toolkit
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from datetime import date
import pandas as pd

In [2]:
# import sentimental data
amazon_df = pd.read_csv('amazon_df.csv')
gme_df = pd.read_csv('gme_df.csv')
kodak_df = pd.read_csv('kodak_df.csv')
facebook_df = pd.read_csv('fb_df.csv')
apple_df = pd.read_csv('new_data/aapl_df.csv')
baba_df = pd.read_csv('new_data/baba_df.csv')
goog_df = pd.read_csv('new_data/goog_df.csv')
jnj_df = pd.read_csv('new_data/jnj_df.csv')
pfe_df = pd.read_csv('new_data/pfe_df.csv')
tsla_df = pd.read_csv('new_data/tsla_df.csv')

In [3]:
# renaming columns
amazon_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
gme_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
kodak_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
facebook_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
goog_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
apple_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
baba_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
jnj_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
pfe_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
tsla_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)

# dropping columns

amazon_df.drop(columns=['Unnamed: 0'], inplace=True)
gme_df.drop(columns=['Unnamed: 0'], inplace=True)
kodak_df.drop(columns=['Unnamed: 0'], inplace=True)
facebook_df.drop(columns=['Unnamed: 0'], inplace=True)
apple_df.drop(columns=['Unnamed: 0'], inplace=True)
goog_df.drop(columns=['Unnamed: 0'], inplace=True)
baba_df.drop(columns=['Unnamed: 0'], inplace=True)
jnj_df.drop(columns=['Unnamed: 0'], inplace=True)
pfe_df.drop(columns=['Unnamed: 0'], inplace=True)
tsla_df.drop(columns=['Unnamed: 0'], inplace=True)

In [4]:
# import price data
amazon_price_df = pd.read_csv('price/AMZN_1.csv')
gme_price_df = pd.read_csv('price/GME_1.csv')
kodak_price_df = pd.read_csv('price/KODK_1.csv')
facebook_price_df = pd.read_csv('price/FB_1.csv')
apple_price_df = pd.read_csv('price/AAPL.csv')
baba_price_df = pd.read_csv('price/BABA.csv')
goog_price_df = pd.read_csv('price/GOOG.csv')
jnj_price_df = pd.read_csv('price/JNJ.csv')
pfe_price_df = pd.read_csv('price/PFE.csv')
tsla_price_df = pd.read_csv('price/TSLA.csv')

In [5]:
# merging DB

amazon_df = pd.merge(amazon_df, amazon_price_df, how="outer", on=["Date", "Date"])
gme_df = pd.merge(gme_df, gme_price_df, how="outer", on=["Date", "Date"] )
kodak_df = pd.merge(kodak_df, kodak_price_df, how="outer", on=["Date", "Date"] )
facebook_df = pd.merge(facebook_df, facebook_price_df, how="outer", on=["Date", "Date"] )
apple_df = pd.merge(apple_df, apple_price_df, how="outer", on=["Date", "Date"] )
baba_df = pd.merge(baba_df, baba_price_df, how="outer", on=["Date", "Date"] )
goog_df = pd.merge(goog_df, goog_price_df, how="outer", on=["Date", "Date"] )
jnj_df = pd.merge(jnj_df, jnj_price_df, how="outer", on=["Date", "Date"] )
pfe_df = pd.merge(pfe_df, pfe_price_df, how="outer", on=["Date", "Date"] )
tsla_df = pd.merge(tsla_df, tsla_price_df, how="outer", on=["Date", "Date"] )


print(amazon_df.shape)
print(kodak_df.shape)
print(gme_df.shape)
print(facebook_df.shape)

(862, 11)
(653, 11)
(726, 11)
(855, 11)


In [6]:
facebook_df.drop(columns=['Date'],inplace=True)
kodak_df.drop(columns=['Date'],inplace=True)
gme_df.drop(columns=['Date'],inplace=True)
amazon_df.drop(columns=['Date'],inplace=True)
apple_df.drop(columns=['Date'],inplace=True)
goog_df.drop(columns=['Date'],inplace=True)
baba_df.drop(columns=['Date'],inplace=True)
jnj_df.drop(columns=['Date'],inplace=True)
pfe_df.drop(columns=['Date'],inplace=True)
tsla_df.drop(columns=['Date'],inplace=True)


In [7]:
facebook_df['retorno'] = facebook_df['Close'].pct_change()
kodak_df['retorno'] = kodak_df['Close'].pct_change()
gme_df['retorno'] = gme_df['Close'].pct_change()
amazon_df['retorno'] = amazon_df['Close'].pct_change()
apple_df['retorno'] = apple_df['Close'].pct_change()
goog_df['retorno'] = goog_df['Close'].pct_change()
baba_df['retorno'] = baba_df['Close'].pct_change()
jnj_df['retorno'] = jnj_df['Close'].pct_change()
pfe_df['retorno'] = pfe_df['Close'].pct_change()
tsla_df['retorno'] = tsla_df['Close'].pct_change()

In [8]:
from sklearn.impute import KNNImputer, SimpleImputer

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
preprocessor = ColumnTransformer([('imputer',  KNNImputer(n_neighbors=1),['Open','Low','Close','Adj Close', 'Volume'])], remainder='passthrough')
filling_na = SimpleImputer(strategy="constant", fill_value=-1000)
my_pipeline = Pipeline(steps=[('preprocessor', preprocessor),('fill_na', filling_na)])

In [ ]:
# gme_np = my_pipeline.fit_transform(gme_df) 
# kodak_np = my_pipeline.fit_transform(kodak_df)
# facebook_np = my_pipeline.fit_transform(facebook_df)
# amazon_np = my_pipeline.fit_transform(amazon_df)
# apple_np = my_pipeline.fit_transform(apple_df)
# google_np = my_pipeline.fit_transform(goog_df)
# baba_np = my_pipeline.fit_transform(baba_df)
# jnj_np = my_pipeline.fit_transform(jnj_df)
# pfe_np = my_pipeline.fit_transform(pfe_df)
# tsla_np = my_pipeline.fit_transform(tsla_df)


In [ ]:
# from tensorflow.keras import models
# from tensorflow.keras import layers
# from tensorflow.keras.optimizers import RMSprop
# from tensorflow.keras.layers.experimental.preprocessing import Normalization
# def init_model():
#     #normalizar o x train
#     normalizer = Normalization()
#     model = models.Sequential()
#     model.add(layers.Masking(mask_value=-1000.))
#     normalizer.adapt(X_tesla_treino)
#     model.add(layers.LSTM(20, return_sequences=True, activation='tanh'))
#     model.add(layers.LSTM(10, return_sequences=False, activation='tanh'))
#     model.add(layers.Dense(5, activation='relu'))
#     model.add(layers.Dense(10, activation='linear'))
    
#   #  model.compile(loss='mse', 
#   #                optimizer='rmsprop', 
#   #                metrics=['mae'])
#     model.compile(loss='mse', 
#                   optimizer=RMSprop(learning_rate=0.0003), 
#                   metrics=['mae'])
    
#     return model

# #init_model().summary()

In [ ]:
# model.fit(x_train,y_train,epochs=20)

### RNN COM UM ATIVO

In [10]:
tsla_df

Positive  Neutral  Negative  Sentimental Score        Open        High  \
0         3.0      1.0       5.0             -0.222  658.390015  666.140015   
1         5.0      2.0       2.0              0.722  670.750000  678.609985   
2         9.0      7.0       9.0              0.280  686.320007  693.280029   
3         7.0      1.0      13.0             -0.381  662.200012  687.239990   
4         0.0      0.0       1.0             -1.500         NaN         NaN   
..        ...      ...       ...                ...         ...         ...   
785       NaN      NaN       NaN                NaN  629.890015  647.200012   
786       NaN      NaN       NaN                NaN  651.989990  662.390015   
787       NaN      NaN       NaN                NaN  659.609985  664.859985   
788       NaN      NaN       NaN                NaN  656.440002  662.169983   
789       NaN      NaN       NaN                NaN  646.359985  648.799988   

            Low       Close   Adj Close      Volume   retorno  
0    637.880005  650.599976  650.599976  20209600.0       NaN  
1    652.840027  653.380005  653.380005  21641200.0  0.004273  
2    666.299988  668.539978  668.539978  20966100.0  0.023202  
3    662.159973  685.700012  685.700012  25927000.0  0.025668  
4           NaN         NaN         NaN         NaN  0.000000  
..          ...         ...         ...         ...       ...  
785  621.289978  646.219971  646.219971  21297100.0  0.003105  
786  640.500000  660.500000  660.500000  15487100.0  0.022098  
787  650.289978  655.289978  655.289978  13953300.0 -0.007888  
788  644.599976  649.260010  649.260010  15105700.0 -0.009202  
789  637.299988  643.380005  643.380005  14581300.0 -0.009056  

[790 rows x 11 columns]

In [11]:
len(tsla_df)

790

In [73]:
y = tsla_df['retorno']
y

0           NaN
1      0.004273
2      0.023202
3      0.025668
4      0.000000
         ...   
785    0.003105
786    0.022098
787   -0.007888
788   -0.009202
789   -0.009056
Name: retorno, Length: 790, dtype: float64

In [74]:
X = tsla_df.drop(columns=['retorno'])
X

Positive  Neutral  Negative  Sentimental Score        Open        High  \
0         3.0      1.0       5.0             -0.222  658.390015  666.140015   
1         5.0      2.0       2.0              0.722  670.750000  678.609985   
2         9.0      7.0       9.0              0.280  686.320007  693.280029   
3         7.0      1.0      13.0             -0.381  662.200012  687.239990   
4         0.0      0.0       1.0             -1.500         NaN         NaN   
..        ...      ...       ...                ...         ...         ...   
785       NaN      NaN       NaN                NaN  629.890015  647.200012   
786       NaN      NaN       NaN                NaN  651.989990  662.390015   
787       NaN      NaN       NaN                NaN  659.609985  664.859985   
788       NaN      NaN       NaN                NaN  656.440002  662.169983   
789       NaN      NaN       NaN                NaN  646.359985  648.799988   

            Low       Close   Adj Close      Volume  
0    637.880005  650.599976  650.599976  20209600.0  
1    652.840027  653.380005  653.380005  21641200.0  
2    666.299988  668.539978  668.539978  20966100.0  
3    662.159973  685.700012  685.700012  25927000.0  
4           NaN         NaN         NaN         NaN  
..          ...         ...         ...         ...  
785  621.289978  646.219971  646.219971  21297100.0  
786  640.500000  660.500000  660.500000  15487100.0  
787  650.289978  655.289978  655.289978  13953300.0  
788  644.599976  649.260010  649.260010  15105700.0  
789  637.299988  643.380005  643.380005  14581300.0  

[790 rows x 10 columns]

In [75]:
X = my_pipeline.fit_transform(X)

In [15]:
X[0:60]

array([[ 6.58390015e+02,  6.37880005e+02,  6.50599976e+02,
         6.50599976e+02,  2.02096000e+07,  3.00000000e+00,
         1.00000000e+00,  5.00000000e+00, -2.22000000e-01,
         6.66140015e+02],
       [ 6.70750000e+02,  6.52840027e+02,  6.53380005e+02,
         6.53380005e+02,  2.16412000e+07,  5.00000000e+00,
         2.00000000e+00,  2.00000000e+00,  7.22000000e-01,
         6.78609985e+02],
       [ 6.86320007e+02,  6.66299988e+02,  6.68539978e+02,
         6.68539978e+02,  2.09661000e+07,  9.00000000e+00,
         7.00000000e+00,  9.00000000e+00,  2.80000000e-01,
         6.93280029e+02],
       [ 6.62200012e+02,  6.62159973e+02,  6.85700012e+02,
         6.85700012e+02,  2.59270000e+07,  7.00000000e+00,
         1.00000000e+00,  1.30000000e+01, -3.81000000e-01,
         6.87239990e+02],
       [ 3.09776733e+02,  3.01849373e+02,  3.09902510e+02,
         3.09902510e+02,  5.53287396e+07,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00, -1.50000000e+00,
        -1.

In [16]:
X_train = []
y_train = []
for i in range(60, 780):
    X_train.append(X[i-60:i])
    y_train.append(y[i])

In [17]:
X_train, y_train = np.array(X_train), np.array(y_train)

In [18]:
X_train.shape

(720, 60, 10)

In [19]:
y_train.shape

(720,)

In [20]:
y_df = pd.DataFrame(y_train)

In [21]:
y_df.isna().sum()

0    0
dtype: int64

In [22]:
X_df = pd.DataFrame(X_train[0])

In [23]:
X_df

0           1           2           3             4     5     6  \
0   658.390015  637.880005  650.599976  650.599976  2.020960e+07   3.0   1.0   
1   670.750000  652.840027  653.380005  653.380005  2.164120e+07   5.0   2.0   
2   686.320007  666.299988  668.539978  668.539978  2.096610e+07   9.0   7.0   
3   662.200012  662.159973  685.700012  685.700012  2.592700e+07   7.0   1.0   
4   309.776733  301.849373  309.902510  309.902510  5.532874e+07   0.0   0.0   
5   653.179993  644.690002  656.950012  656.950012  1.811850e+07   4.0   1.0   
6   628.369995  620.460022  652.809998  652.809998  2.277330e+07   6.0   4.0   
7   664.270020  638.320007  644.650024  644.650024  1.879200e+07   4.0   1.0   
8   681.710022  651.400024  659.580017  659.580017  2.328450e+07   6.0   1.0   
9   309.776733  301.849373  309.902510  309.902510  5.532874e+07   1.0   1.0   
10  309.776733  301.849373  309.902510  309.902510  5.532874e+07   1.0   0.0   
11  309.776733  301.849373  309.902510  309.902510  5.532874e+07   1.0   0.0   
12  678.979980  673.260010  678.900024  678.900024  2.705450e+07  17.0  11.0   
13  683.919983  672.799988  677.919983  677.919983  1.863450e+07   5.0   2.0   
14  679.770020  678.140015  679.700012  679.700012  1.892490e+07   8.0   3.0   
15  684.650024  675.890015  680.760010  680.760010  1.738130e+07   5.0   7.0   
16  671.640015  670.320007  688.719971  688.719971  2.162820e+07   4.0   4.0   
17  309.776733  301.849373  309.902510  309.902510  5.532874e+07   1.0   0.0   
18  309.776733  301.849373  309.902510  309.902510  5.532874e+07   2.0   0.0   
19  689.580017  668.700012  671.869995  671.869995  3.249670e+07   6.0   4.0   
20  674.989990  667.609985  679.820007  679.820007  4.598240e+07  13.0   5.0   
21  632.000000  630.039978  656.570007  656.570007  3.109920e+07  14.0   1.0   
22  618.250000  615.500000  623.710022  623.710022  1.915890e+07   1.0   1.0   
23  624.479980  608.880005  620.830017  620.830017  2.481270e+07   7.0   1.0   
24  309.776733  301.849373  309.902510  309.902510  5.532874e+07   2.0   0.0   
25  309.776733  301.849373  309.902510  309.902510  5.532874e+07   0.0   0.0   
26  613.369995  611.799988  623.309998  623.309998  2.456090e+07   2.0   1.0   
27  601.890015  601.340027  616.599976  616.599976  2.270140e+07   6.0   3.0   
28  597.539978  593.500000  604.869995  604.869995  2.214410e+07   8.0   2.0   
29  616.690002  598.229980  599.359985  599.359985  1.776410e+07   3.0   1.0   
30  612.229980  609.179993  617.690002  617.690002  2.042400e+07  11.0   1.0   
31  309.776733  301.849373  309.902510  309.902510  5.532874e+07   7.0   1.0   
32  610.229980  601.520020  609.890015  609.890015  1.620530e+07  13.0   8.0   
33  603.880005  600.500000  610.119995  610.119995  2.391960e+07   6.0   5.0   
34  602.169983  597.630005  598.780029  598.780029  1.658460e+07   0.0   4.0   
35  623.010010  595.500000  603.590027  603.590027  2.605340e+07  11.0   5.0   
36  591.830017  582.880005  605.130005  605.130005  2.254370e+07   3.0   6.0   
37  309.776733  301.849373  309.902510  309.902510  5.532874e+07   1.0   2.0   
38  309.776733  301.849373  309.902510  309.902510  5.532874e+07   0.0   0.0   
39  579.710022  577.200012  599.049988  599.049988  2.403690e+07   6.0   2.0   
40  601.799988  571.219971  572.840027  572.840027  3.011190e+07   3.0   6.0   
41  620.130005  599.140015  605.119995  605.119995  2.330280e+07   6.0   7.0   
42  627.799988  620.549988  623.900024  623.900024  1.808490e+07   5.0   2.0   
43  309.776733  301.849373  309.902510  309.902510  5.532874e+07   0.0   0.0   
44  309.776733  301.849373  309.902510  309.902510  5.532874e+07   0.0   1.0   
45  309.776733  301.849373  309.902510  309.902510  5.532874e+07   1.0   2.0   
46  628.500000  622.380005  625.219971  625.219971  2.273700e+07   3.0   2.0   
47  620.239990  616.210022  630.849976  630.849976  2.637060e+07   5.0   8.0   
48  607.559998  601.500000  619.130005  619.130005  2.863930e+07   5.0  12.0   
49  607.30999

In [24]:
from tensorflow.keras import models
from tensorflow.keras import layers, Sequential
from tensorflow.keras.layers import LSTM, Dropout, Dense
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.layers.experimental.preprocessing import Normalization

def init_article_model():
    model = Sequential()
    #Adding the first LSTM layer and some Dropout regularisation
    model.add(LSTM(units = 50, return_sequences = True, input_shape=(60,10)))
    model.add(Dropout(0.2))
    # Adding a second LSTM layer and some Dropout regularisation
    model.add(LSTM(units = 50, return_sequences = True))
    model.add(Dropout(0.2))
    # Adding a third LSTM layer and some Dropout regularisation
    model.add(LSTM(units = 50, return_sequences = True))
    model.add(Dropout(0.2))
    # Adding a fourth LSTM layer and some Dropout regularisation
    model.add(LSTM(units = 50))
    model.add(Dropout(0.2))
    # Adding the output layer
    model.add(Dense(units = 1))

    # Compiling the RNN
    model.compile(optimizer = 'adam', loss = 'mse')
    
    return model

def tanise_model():
    #normalizar o x train
    normalizer = Normalization()
    model = models.Sequential()
    model.add(layers.Masking(mask_value=-1000.))
    normalizer.adapt(X_train)
    model.add(layers.LSTM(20, return_sequences=True, activation='tanh'))
    model.add(layers.LSTM(10, return_sequences=False, activation='tanh'))
    model.add(layers.Dense(5, activation='relu'))
    model.add(layers.Dense(10, activation='linear'))
    
  #  model.compile(loss='mse', 
  #                optimizer='rmsprop', 
  #                metrics=['mae'])
    model.compile(loss='mse', 
                  optimizer=RMSprop(learning_rate=0.0003), 
                  metrics=['mae'])
    
    return model

In [79]:
# Fitting the RNN to the Training set
tesla_model = init_article_model()
fitted = tesla_model.fit(X_train, y_train, epochs = 2, batch_size = 5)

Epoch 1/2
144/144 [==============================] - 28s 126ms/step - loss: 0.0034
Epoch 2/2
144/144 [==============================] - 17s 115ms/step - loss: 0.0020


In [26]:
X_test = X[781:790]
X_test

array([[ 5.74640007e+01,  5.74339981e+01,  5.83619995e+01,
         5.83619995e+01,  3.95970000e+07,  5.00000000e+00,
         3.00000000e+00,  2.00000000e+00,  7.50000000e-01,
         5.92340012e+01],
       [ 5.76599998e+01,  5.67760010e+01,  5.71759987e+01,
         5.71759987e+01,  2.73945000e+07,  1.00000000e+00,
         2.00000000e+00,  6.00000000e+00, -6.11000000e-01,
         5.78880005e+01],
       [ 5.65239983e+01,  5.62560005e+01,  5.78359985e+01,
         5.78359985e+01,  4.05520000e+07,  2.00000000e+00,
         2.00000000e+00,  3.00000000e+00,  7.10000000e-02,
         5.78400002e+01],
       [ 6.54679993e+02,  6.42200012e+02,  6.44219971e+02,
         6.44219971e+02,  1.63398000e+07, -1.00000000e+03,
        -1.00000000e+03, -1.00000000e+03, -1.00000000e+03,
         6.56700012e+02],
       [ 6.29890015e+02,  6.21289978e+02,  6.46219971e+02,
         6.46219971e+02,  2.12971000e+07, -1.00000000e+03,
        -1.00000000e+03, -1.00000000e+03, -1.00000000e+03,
         6.

In [ ]:
# # Getting the predicted stock price of 2017
# dataset_train = X.iloc[:780, :]
# dataset_test = y.iloc[780,:]
# dataset_total = pd.concat((dataset_train, dataset_test), axis = 0)
# # inputs = dataset_total[len(dataset_total) - len(dataset_test) - 60:].values
# # inputs = inputs.reshape(-1,1)
# # inputs = sc.transform(inputs)
# # X_test = []
# for i in range(60, 519):
#     X_test.append(inputs[i-60:i, 0])
# X_test = np.array(X_test)
# X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
# print(X_test.shape)

In [39]:
len(X)

790

In [40]:
len(X_train)

720

In [87]:
X_test = []
y_test = []
for i in range(720, len(X)):
    X_test.append(X[i-60:i])
    y_test.append(y[i])

In [88]:
X_test = np.array(X_test)
X_test

array([[[ 4.65979996e+01,  4.57500000e+01,  4.58019981e+01, ...,
          1.00000000e+00,  0.00000000e+00,  4.71539993e+01],
        [ 3.09776733e+02,  3.01849373e+02,  3.09902510e+02, ...,
          2.00000000e+00, -5.00000000e-01, -1.00000000e+03],
        [ 4.72099991e+01,  4.67620010e+01,  4.70019989e+01, ...,
          0.00000000e+00,  1.50000000e+00,  4.77919998e+01],
        ...,
        [ 4.38279991e+01,  4.27000008e+01,  4.34199982e+01, ...,
          1.00000000e+00,  1.18200000e+00,  4.41800003e+01],
        [ 4.20499992e+01,  4.18019981e+01,  4.25760002e+01, ...,
          3.00000000e+00,  1.88000000e-01,  4.33880005e+01],
        [ 3.09776733e+02,  3.01849373e+02,  3.09902510e+02, ...,
          1.00000000e+00, -1.50000000e+00, -1.00000000e+03]],

       [[ 3.09776733e+02,  3.01849373e+02,  3.09902510e+02, ...,
          2.00000000e+00, -5.00000000e-01, -1.00000000e+03],
        [ 4.72099991e+01,  4.67620010e+01,  4.70019989e+01, ...,
          0.00000000e+00,  1.50000000e

In [89]:
X_test.shape

(70, 60, 10)

In [45]:
np.array(X_test).shape

(70, 60, 10)

In [47]:
np.array(y_test).shape

(70,)

In [57]:
X_train.shape

(720, 60, 10)

In [64]:
X_test = X[721:]
X_test

array([[ 4.10000000e+01,  4.07000008e+01,  4.09000015e+01,
         4.09000015e+01,  8.00175000e+07,  1.00000000e+00,
         2.00000000e+00,  2.00000000e+00,  1.00000000e-01,
         4.21679993e+01],
       [ 4.08880005e+01,  4.03600006e+01,  4.11899986e+01,
         4.11899986e+01,  1.01211000e+08,  9.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.50000000e+00,
         4.22000008e+01],
       [ 3.97360001e+01,  3.83699989e+01,  3.93180008e+01,
         3.93180008e+01,  6.75540000e+07,  2.00000000e+00,
         1.00000000e+00,  2.00000000e+00,  2.00000000e-01,
         4.02560005e+01],
       [ 3.62200012e+01,  3.59220009e+01,  3.87200012e+01,
         3.87200012e+01,  6.90375000e+07,  5.00000000e+00,
         4.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         3.87960014e+01],
       [ 3.71020012e+01,  3.53979988e+01,  3.57939987e+01,
         3.57939987e+01,  6.53220000e+07,  3.00000000e+00,
         5.00000000e+00,  5.00000000e+00,  1.54000000e-01,
         3.

In [91]:
tesla_model.predict(X_test)

array([[-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0.00715138],
       [-0

In [93]:
tesla_model.predict(X_test).shape

(70, 1)