In [18]:
# import toolkit
# import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from datetime import date
import pandas as pd

In [19]:
# import sentimental data
amazon_df = pd.read_csv('amazon_df.csv')
gme_df = pd.read_csv('gme_df.csv')
kodak_df = pd.read_csv('kodak_df.csv')
facebook_df = pd.read_csv('fb_df.csv')

In [20]:
# renaming columns
amazon_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
gme_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
kodak_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)
facebook_df.rename({'0':'Date', '1':'Positive', '2':'Neutral', '3':'Negative', '4':'Sentimental Score'}, axis=1, inplace=True)

# dropping columns

amazon_df.drop(columns=['Unnamed: 0'], inplace=True)
gme_df.drop(columns=['Unnamed: 0'], inplace=True)
kodak_df.drop(columns=['Unnamed: 0'], inplace=True)
facebook_df.drop(columns=['Unnamed: 0'], inplace=True)


In [21]:
# import price data
amazon_price_df = pd.read_csv('price/AMZN_1.csv')
gme_price_df = pd.read_csv('price/GME_1.csv')
kodak_price_df = pd.read_csv('price/KODK_1.csv')
facebook_price_df = pd.read_csv('price/FB_1.csv')

In [26]:
# merging DB

amazon_df = pd.merge(amazon_df, amazon_price_df, how="outer", on=["Date", "Date"]).fillna(-1000,inplace=True)
gme_df = pd.merge(gme_df, gme_price_df, how="outer", on=["Date", "Date"] ).fillna(-1000,inplace=True)
kodak_df = pd.merge(kodak_df, kodak_price_df, how="outer", on=["Date", "Date"] ).fillna(-1000,inplace=True)
facebook_df = pd.merge(facebook_df, facebook_price_df, how="outer", on=["Date", "Date"] ).fillna(-1000,inplace=True)

print(amazon_df.shape)
print(kodak_df.shape)
print(gme_df.shape)
print(facebook_df.shape)

AttributeError: 'NoneType' object has no attribute 'shape'

In [23]:
facebook_df

Date  Positive  Neutral  Negative  Sentimental Score        Open  \
0    2021-07-24       1.0      0.0       0.0              1.500         NaN   
1    2021-07-23      12.0      6.0       7.0              0.540  360.910004   
2    2021-07-22       4.0      4.0       1.0              0.944  346.679993   
3    2021-07-21       3.0      2.0       2.0              0.500  341.500000   
4    2021-07-20       3.0      2.0       8.0             -0.423  338.799988   
..          ...       ...      ...       ...                ...         ...   
850  2019-02-13       NaN      NaN       NaN                NaN  165.380005   
851  2019-02-15       NaN      NaN       NaN                NaN  164.509995   
852  2019-02-22       NaN      NaN       NaN                NaN  160.580002   
853  2019-03-04       NaN      NaN       NaN                NaN  163.899994   
854  2021-07-26       NaN      NaN       NaN                NaN  369.579987   

           High         Low       Close   Adj Close      Volume  
0           NaN         NaN         NaN         NaN         NaN  
1    375.329987  357.190002  369.790009  369.790009  33680400.0  
2    351.540009  345.209991  351.190002  351.190002  12385400.0  
3    346.519989  341.250000  346.230011  346.230011   9279700.0  
4    343.450012  334.500000  341.660004  341.660004  11024300.0  
..          ...         ...         ...         ...         ...  
850  166.220001  163.729996  164.070007  164.070007  14205100.0  
851  164.699997  160.860001  162.500000  162.500000  15504400.0  
852  162.410004  160.309998  161.889999  161.889999  15858500.0  
853  167.500000  163.830002  167.369995  167.369995  18894700.0  
854  374.440002  368.220001  372.459991  372.459991  14910300.0  

[855 rows x 11 columns]

In [324]:
gme_np = gme_df.to_numpy() 
kodak_np = kodak_df.to_numpy()
facebook_np = facebook_df.to_numpy()
amazon_np = amazon_df.to_numpy()

In [25]:
gme_df.isna().sum()

Date                   0
Positive             303
Neutral              303
Negative             303
Sentimental Score    303
Open                  90
High                  90
Low                   90
Close                 90
Adj Close             90
Volume                90
dtype: int64

In [325]:
news_price_np = np.array([gme_np,kodak_np,amazon_np,facebook_np])

/var/folders/g9/dk8kk1tn5ys_km_c5w3rh3380000gp/T/ipykernel_54097/580881537.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  news_price_np = np.array([gme_np,kodak_np,amazon_np,facebook_np])


In [184]:
#reddit_day.fillna(-1000,inplace=True)
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [326]:
news_price_np_pad = pad_sequences(news_price_np,value=-1000, dtype='float32') # int32 by default
news_price_np_pad

array([[[-1.00000e+03, -1.00000e+03, -1.00000e+03, ..., -1.00000e+03,
         -1.00000e+03, -1.00000e+03],
        [-1.00000e+03, -1.00000e+03, -1.00000e+03, ..., -1.00000e+03,
         -1.00000e+03, -1.00000e+03],
        [-1.00000e+03, -1.00000e+03, -1.00000e+03, ..., -1.00000e+03,
         -1.00000e+03, -1.00000e+03],
        ...,
        [-1.00000e+03, -1.00000e+03, -1.00000e+03, ...,  1.76150e+02,
          1.78850e+02,  1.41300e+06],
        [-1.00000e+03, -1.00000e+03, -1.00000e+03, ...,  1.73840e+02,
          1.80360e+02,  1.31290e+06],
        [-1.00000e+03, -1.00000e+03, -1.00000e+03, ...,  1.78760e+02,
          1.83940e+02,  1.25540e+06]],

       [[-1.00000e+03, -1.00000e+03, -1.00000e+03, ..., -1.00000e+03,
         -1.00000e+03, -1.00000e+03],
        [-1.00000e+03, -1.00000e+03, -1.00000e+03, ..., -1.00000e+03,
         -1.00000e+03, -1.00000e+03],
        [-1.00000e+03, -1.00000e+03, -1.00000e+03, ..., -1.00000e+03,
         -1.00000e+03, -1.00000e+03],
        ...,


In [327]:
x_train = news_price_np_pad[:,:-30]
x_test = news_price_np_pad[:,-30:]

array([[[-1.00000e+03, -1.00000e+03, -1.00000e+03, ..., -1.00000e+03,
         -1.00000e+03, -1.00000e+03],
        [-1.00000e+03, -1.00000e+03, -1.00000e+03, ..., -1.00000e+03,
         -1.00000e+03, -1.00000e+03],
        [-1.00000e+03, -1.00000e+03, -1.00000e+03, ..., -1.00000e+03,
         -1.00000e+03, -1.00000e+03],
        ...,
        [-1.00000e+03, -1.00000e+03, -1.00000e+03, ...,  1.72300e+01,
          1.73700e+01,  4.96150e+06],
        [-1.00000e+03, -1.00000e+03, -1.00000e+03, ...,  1.70750e+02,
          1.76190e+02,  3.76030e+06],
        [-1.00000e+03, -1.00000e+03, -1.00000e+03, ...,  1.56220e+02,
          1.59920e+02,  4.29350e+06]],

       [[-1.00000e+03, -1.00000e+03, -1.00000e+03, ..., -1.00000e+03,
         -1.00000e+03, -1.00000e+03],
        [-1.00000e+03, -1.00000e+03, -1.00000e+03, ..., -1.00000e+03,
         -1.00000e+03, -1.00000e+03],
        [-1.00000e+03, -1.00000e+03, -1.00000e+03, ..., -1.00000e+03,
         -1.00000e+03, -1.00000e+03],
        ...,


In [328]:
from sklearn.impute import KNNImputer
y_target  = [gme_y,kodak_y,amazon_y,facebook_y]
y_target_imputed = []
for i in y_target:
    y = KNNImputer(n_neighbors=1).fit_transform([i])
    y_target_imputed.append(y)

In [243]:
kodak_df.shape

(653, 9)

In [246]:
y_train

[array([[166.820007, 167.619995, 180.059998, 189.25    , 191.229996,
         191.380005, 190.660004, 199.559998, 202.830002, 204.360001,
         214.139999, 210.880005, 213.25    , 209.509995, 212.309998,
         219.339996, 220.399994, 200.369995, 213.820007, 223.589996,
         222.970001, 222.5     , 229.440002, 233.339996, 220.389999,
         302.559998, 300.      , 280.01001 , 248.360001, 258.179993,
         282.23999 , 249.020004, 222.      , 254.130005, 242.559998,
         209.429993, 180.009995, 176.789993, 170.490005, 168.830002,
         180.669998, 180.600006, 164.5     , 144.789993, 146.919998,
         143.220001, 161.110001, 161.009995, 159.479996, 160.729996,
         162.199997, 173.589996, 178.580002, 177.770004, 168.929993,
         151.179993, 151.169998, 158.509995, 158.529999, 164.369995,
         154.690002, 156.440002, 166.529999, 140.990005, 141.089996,
         158.360001, 170.259995, 177.970001, 184.5     , 186.949997,
         191.449997, 189.820007, 1

In [352]:
print(amazon_df.shape)
print(amazon_y.shape)

(862, 9)
(862,)


In [332]:
y_reshaped = np.array(y_target_imputed).reshape(4,636,1)
y_train = y_reshaped[:,:-30]
y_test = y_reshaped[:,-30:]

In [333]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(4, 832, 9)
(4, 606, 1)
(4, 30, 9)
(4, 30, 1)


In [360]:
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.layers.experimental.preprocessing import Normalization
def init_model():
    #normalizar o x train
    normalizer = Normalization()
    model = models.Sequential()
    model.add(layers.Masking(mask_value=-1000.,input_shape=(832, 9)))
    
    normalizer.adapt(x_train)
    #model.add(layers.LSTM(20, return_sequences=False, activation='tanh'))
    model.add(layers.LSTM(10, return_sequences=False, activation='tanh'))
    model.add(layers.Dense(5, activation='relu'))
    model.add(layers.Dense(1, activation='linear'))
    
  #  model.compile(loss='mse', 
  #                optimizer='rmsprop', 
  #                metrics=['mae'])
    model.compile(loss='mse', 
                  optimizer=RMSprop(learning_rate=0.0003), 
                  metrics=['mae'])
    
    return model

#init_model().summary()

In [361]:
model=init_model()

In [362]:
model.fit(x_train,y_train,epochs=2)

Epoch 1/2
1/1 [==============================] - 11s 11s/step - loss: 1613140.2500 - mae: 678.9153
Epoch 2/2
1/1 [==============================] - 1s 1s/step - loss: 1613127.5000 - mae: 678.9059


In [267]:
y_train.shape

(0, 636, 1)

In [337]:
model.predict(x_test)

array([[0.37280577],
       [0.37280577],
       [0.37280577],
       [0.19384885]], dtype=float32)

In [ ]:
#gme_np,kodak_np,amazon_np,facebook_np
y_